#!/bin/sh

###############################################
#                                             #
# This script should be put somewhere inside  #
# the executables user's path.                #
#                                             #
###############################################

# subtitute with user name
USER=oren

sudo -u $USER ediff /sudo::$1 /sudo::$2
