#!/bin/sh

###############################################
#                                             #
# This script should be put in /usr/local/bin #
# or some other executables system path.      #
#                                             #
###############################################

emacsclient --eval "(ediff-files \"$1\" \"$2\")"
